import type { S3ProviderPreset } from '$shared/types';

export const S3_PROVIDERS: Record<string, S3ProviderPreset> = {
  aws: {
    name: 'AWS S3',
    regions: [
      { id: 'us-east-1', name: '美国东部 N. Virginia', endpoint: 's3.us-east-1.amazonaws.com' },
      { id: 'us-east-2', name: '美国东部 Ohio', endpoint: 's3.us-east-2.amazonaws.com' },
      { id: 'us-west-1', name: '美国西部 N. California', endpoint: 's3.us-west-1.amazonaws.com' },
      { id: 'us-west-2', name: '美国西部 Oregon', endpoint: 's3.us-west-2.amazonaws.com' },
      { id: 'ap-east-1', name: '亚太 香港', endpoint: 's3.ap-east-1.amazonaws.com' },
      { id: 'ap-south-1', name: '亚太 孟买', endpoint: 's3.ap-south-1.amazonaws.com' },
      { id: 'ap-northeast-1', name: '亚太 东京', endpoint: 's3.ap-northeast-1.amazonaws.com' },
      { id: 'ap-northeast-2', name: '亚太 首尔', endpoint: 's3.ap-northeast-2.amazonaws.com' },
      { id: 'ap-northeast-3', name: '亚太 大阪', endpoint: 's3.ap-northeast-3.amazonaws.com' },
      { id: 'ap-southeast-1', name: '亚太 新加坡', endpoint: 's3.ap-southeast-1.amazonaws.com' },
      { id: 'ap-southeast-2', name: '亚太 悉尼', endpoint: 's3.ap-southeast-2.amazonaws.com' },
      { id: 'eu-central-1', name: '欧洲 法兰克福', endpoint: 's3.eu-central-1.amazonaws.com' },
      { id: 'eu-west-1', name: '欧洲 爱尔兰', endpoint: 's3.eu-west-1.amazonaws.com' },
      { id: 'eu-west-2', name: '欧洲 伦敦', endpoint: 's3.eu-west-2.amazonaws.com' },
      { id: 'eu-west-3', name: '欧洲 巴黎', endpoint: 's3.eu-west-3.amazonaws.com' },
    ],
    forcePathStyle: false,
  },
  aliyun: {
    name: '阿里云 OSS',
    regions: [
      { id: 'oss-cn-hangzhou', name: '华东1 杭州', endpoint: 'oss-cn-hangzhou.aliyuncs.com' },
      { id: 'oss-cn-shanghai', name: '华东2 上海', endpoint: 'oss-cn-shanghai.aliyuncs.com' },
      { id: 'oss-cn-nanjing', name: '华东5 南京', endpoint: 'oss-cn-nanjing.aliyuncs.com' },
      { id: 'oss-cn-fuzhou', name: '华东6 福州', endpoint: 'oss-cn-fuzhou.aliyuncs.com' },
      { id: 'oss-cn-qingdao', name: '华北1 青岛', endpoint: 'oss-cn-qingdao.aliyuncs.com' },
      { id: 'oss-cn-beijing', name: '华北2 北京', endpoint: 'oss-cn-beijing.aliyuncs.com' },
      { id: 'oss-cn-zhangjiakou', name: '华北3 张家口', endpoint: 'oss-cn-zhangjiakou.aliyuncs.com' },
      { id: 'oss-cn-huhehaote', name: '华北5 呼和浩特', endpoint: 'oss-cn-huhehaote.aliyuncs.com' },
      { id: 'oss-cn-shenzhen', name: '华南1 深圳', endpoint: 'oss-cn-shenzhen.aliyuncs.com' },
      { id: 'oss-cn-guangzhou', name: '华南2 广州', endpoint: 'oss-cn-guangzhou.aliyuncs.com' },
      { id: 'oss-cn-chengdu', name: '西南1 成都', endpoint: 'oss-cn-chengdu.aliyuncs.com' },
      { id: 'oss-cn-hongkong', name: '香港', endpoint: 'oss-cn-hongkong.aliyuncs.com' },
      { id: 'oss-us-west-1', name: '美国西部 硅谷', endpoint: 'oss-us-west-1.aliyuncs.com' },
      { id: 'oss-us-east-1', name: '美国东部 弗吉尼亚', endpoint: 'oss-us-east-1.aliyuncs.com' },
      { id: 'oss-ap-southeast-1', name: '亚太东南1 新加坡', endpoint: 'oss-ap-southeast-1.aliyuncs.com' },
      { id: 'oss-ap-southeast-2', name: '亚太东南2 悉尼', endpoint: 'oss-ap-southeast-2.aliyuncs.com' },
      { id: 'oss-ap-southeast-3', name: '亚太东南3 吉隆坡', endpoint: 'oss-ap-southeast-3.aliyuncs.com' },
      { id: 'oss-ap-southeast-5', name: '亚太东南5 雅加达', endpoint: 'oss-ap-southeast-5.aliyuncs.com' },
      { id: 'oss-ap-northeast-1', name: '亚太东北1 东京', endpoint: 'oss-ap-northeast-1.aliyuncs.com' },
      { id: 'oss-ap-south-1', name: '亚太南部1 孟买', endpoint: 'oss-ap-south-1.aliyuncs.com' },
      { id: 'oss-eu-central-1', name: '欧洲中部1 法兰克福', endpoint: 'oss-eu-central-1.aliyuncs.com' },
      { id: 'oss-eu-west-1', name: '欧洲西部1 伦敦', endpoint: 'oss-eu-west-1.aliyuncs.com' },
    ],
    forcePathStyle: false,
  },
  tencent: {
    name: '腾讯云 COS',
    regions: [
      { id: 'ap-beijing', name: '北京', endpoint: 'cos.ap-beijing.myqcloud.com' },
      { id: 'ap-nanjing', name: '南京', endpoint: 'cos.ap-nanjing.myqcloud.com' },
      { id: 'ap-shanghai', name: '上海', endpoint: 'cos.ap-shanghai.myqcloud.com' },
      { id: 'ap-guangzhou', name: '广州', endpoint: 'cos.ap-guangzhou.myqcloud.com' },
      { id: 'ap-chengdu', name: '成都', endpoint: 'cos.ap-chengdu.myqcloud.com' },
      { id: 'ap-chongqing', name: '重庆', endpoint: 'cos.ap-chongqing.myqcloud.com' },
      { id: 'ap-hongkong', name: '香港', endpoint: 'cos.ap-hongkong.myqcloud.com' },
      { id: 'ap-singapore', name: '新加坡', endpoint: 'cos.ap-singapore.myqcloud.com' },
      { id: 'ap-mumbai', name: '孟买', endpoint: 'cos.ap-mumbai.myqcloud.com' },
      { id: 'ap-jakarta', name: '雅加达', endpoint: 'cos.ap-jakarta.myqcloud.com' },
      { id: 'ap-seoul', name: '首尔', endpoint: 'cos.ap-seoul.myqcloud.com' },
      { id: 'ap-bangkok', name: '曼谷', endpoint: 'cos.ap-bangkok.myqcloud.com' },
      { id: 'ap-tokyo', name: '东京', endpoint: 'cos.ap-tokyo.myqcloud.com' },
      { id: 'na-siliconvalley', name: '硅谷', endpoint: 'cos.na-siliconvalley.myqcloud.com' },
      { id: 'na-ashburn', name: '弗吉尼亚', endpoint: 'cos.na-ashburn.myqcloud.com' },
      { id: 'na-toronto', name: '多伦多', endpoint: 'cos.na-toronto.myqcloud.com' },
      { id: 'sa-saopaulo', name: '圣保罗', endpoint: 'cos.sa-saopaulo.myqcloud.com' },
      { id: 'eu-frankfurt', name: '法兰克福', endpoint: 'cos.eu-frankfurt.myqcloud.com' },
    ],
    forcePathStyle: false,
  },
  qiniu: {
    name: '七牛云 Kodo',
    regions: [
      { id: 'cn-east-1', name: '华东-浙江', endpoint: 's3-cn-east-1.qiniucs.com' },
      { id: 'cn-east-2', name: '华东-浙江2', endpoint: 's3-cn-east-2.qiniucs.com' },
      { id: 'cn-north-1', name: '华北-河北', endpoint: 's3-cn-north-1.qiniucs.com' },
      { id: 'cn-south-1', name: '华南-广东', endpoint: 's3-cn-south-1.qiniucs.com' },
      { id: 'us-north-1', name: '北美-洛杉矶', endpoint: 's3-us-north-1.qiniucs.com' },
      { id: 'ap-southeast-1', name: '亚太-新加坡', endpoint: 's3-ap-southeast-1.qiniucs.com' },
    ],
    forcePathStyle: false,
  },
  r2: {
    name: 'Cloudflare R2',
    regions: [
      { id: 'auto', name: '自动', endpoint: '' }, // 需要用户填写 account ID
    ],
    forcePathStyle: true,
  },
  minio: {
    name: 'MinIO',
    regions: [
      { id: 'custom', name: '自定义', endpoint: '' },
    ],
    forcePathStyle: true,
  },
  backblaze: {
    name: 'Backblaze B2',
    regions: [
      { id: 'us-west-000', name: '美国西部 Phoenix', endpoint: 's3.us-west-000.backblazeb2.com' },
      { id: 'us-west-001', name: '美国西部 Sacramento', endpoint: 's3.us-west-001.backblazeb2.com' },
      { id: 'us-west-002', name: '美国西部 Phoenix 2', endpoint: 's3.us-west-002.backblazeb2.com' },
      { id: 'us-west-004', name: '美国西部 Phoenix 4', endpoint: 's3.us-west-004.backblazeb2.com' },
      { id: 'eu-central-003', name: '欧洲中部 Amsterdam', endpoint: 's3.eu-central-003.backblazeb2.com' },
    ],
    forcePathStyle: false,
  },
  wasabi: {
    name: 'Wasabi',
    regions: [
      { id: 'us-east-1', name: '美国东部 N. Virginia', endpoint: 's3.us-east-1.wasabisys.com' },
      { id: 'us-east-2', name: '美国东部 N. Virginia 2', endpoint: 's3.us-east-2.wasabisys.com' },
      { id: 'us-central-1', name: '美国中部 Texas', endpoint: 's3.us-central-1.wasabisys.com' },
      { id: 'us-west-1', name: '美国西部 Oregon', endpoint: 's3.us-west-1.wasabisys.com' },
      { id: 'eu-central-1', name: '欧洲中部 Amsterdam', endpoint: 's3.eu-central-1.wasabisys.com' },
      { id: 'eu-central-2', name: '欧洲中部 Frankfurt', endpoint: 's3.eu-central-2.wasabisys.com' },
      { id: 'eu-west-1', name: '欧洲西部 London', endpoint: 's3.eu-west-1.wasabisys.com' },
      { id: 'eu-west-2', name: '欧洲西部 Paris', endpoint: 's3.eu-west-2.wasabisys.com' },
      { id: 'ap-northeast-1', name: '亚太东北 Tokyo', endpoint: 's3.ap-northeast-1.wasabisys.com' },
      { id: 'ap-northeast-2', name: '亚太东北 Osaka', endpoint: 's3.ap-northeast-2.wasabisys.com' },
      { id: 'ap-southeast-1', name: '亚太东南 Singapore', endpoint: 's3.ap-southeast-1.wasabisys.com' },
      { id: 'ap-southeast-2', name: '亚太东南 Sydney', endpoint: 's3.ap-southeast-2.wasabisys.com' },
    ],
    forcePathStyle: false,
  },
  custom: {
    name: '自定义 S3 兼容',
    regions: [
      { id: 'custom', name: '自定义', endpoint: '' },
    ],
    forcePathStyle: false,
  },
};

// 获取默认的空 S3 配置
export function getDefaultS3Config(): import('$shared/types').S3Config {
  return {
    provider: '',
    endpoint: '',
    region: '',
    accessKeyId: '',
    secretAccessKey: '',
    bucket: '',
    publicUrl: '',
    pathPrefix: '',
    forcePathStyle: false,
    urlSuffix: '',
  };
}
